# see https://pyup.io/docs/configuration/ for all available options

schedule: "every two weeks on tuesday"

update: insecure

search: False
requirements:
  - requirements.in:
    update: insecure
  - requirements_for_test.txt:
    update: insecure
